<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Title>RZ.TaskScheduler</Title>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Copyright>(c) 2026 by Roger Zander</Copyright>
		<Description>a simple TaskScheduler</Description>
		<ProductName>RZ.TaskScheduler</ProductName>
		<Company>Zander - Tools</Company>
		<FileVersion>1.0.7.0</FileVersion>
		<PackageVersion>1.0.7</PackageVersion>
		<PackageProjectUrl>https://github.com/rzander/RZ.TaskScheduler</PackageProjectUrl>
		<RepositoryUrl>https://github.com/rzander/RZ.TaskScheduler</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	</Target>
	
</Project>
